# FILE DESCRIPTION:
#
# This file declares the different controller types which can then be
# instanciated by the controller manager. In this file only controllers
# for the arm are declared (no gripper).
# 
# See also: http://wiki.ros.org/joint_trajectory_controller?distro=lunar
#

psir:
    ## joint_names
    joint_names: [psir_joint_1, psir_joint_2, psir_joint_3, psir_joint_4, psir_joint_5, psir_joint_6]

    ## control_mode_adapter
    max_command_silence: 0.5

    ## joint_state_controller (needed to obtain /joint_states)

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    ## joint trajectory controller
    joint_trajectory_controller:
        type: position_controllers/JointTrajectoryController
        joints:
            - psir_joint_1
            - psir_joint_2
            - psir_joint_3
            - psir_joint_4
            - psir_joint_5
            - psir_joint_6
        constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05
            psir_joint_1: {trajectory: 0.157, goal: 0.01}
            psir_joint_2: {trajectory: 0.157, goal: 0.01}
            psir_joint_3: {trajectory: 0.157, goal: 0.01}
            psir_joint_4: {trajectory: 0.157, goal: 0.01}
            psir_joint_5: {trajectory: 0.157, goal: 0.01}
            psir_joint_6: {trajectory: 0.157, goal: 0.01}
        stop_trajectory_duration: 0.5
        state_publish_rate:  25
        action_monitor_rate: 10
        required_drive_mode: 7

## position controller
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - psir_joint_1
     - psir_joint_2
     - psir_joint_3
     - psir_joint_4
     - psir_joint_5
     - psir_joint_6
  required_drive_mode: 1

joint_group_interpol_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - psir_joint_1
     - psir_joint_2
     - psir_joint_3
     - psir_joint_4
     - psir_joint_5
     - psir_joint_6
  required_drive_mode: 7

psir_joint_1_position_controller:
  type: position_controllers/JointPositionController
  joint: psir_joint_1
  required_drive_mode: 1
psir_joint_2_position_controller:
  type: position_controllers/JointPositionController
  joint: psir_joint_2
  required_drive_mode: 1
psir_joint_3_position_controller:
  type: position_controllers/JointPositionController
  joint: psir_joint_3
  required_drive_mode: 1
psir_joint_4_position_controller:
  type: position_controllers/JointPositionController
  joint: psir_joint_4
  required_drive_mode: 1
psir_joint_5_position_controller:
  type: position_controllers/JointPositionController
  joint: psir_joint_5
  required_drive_mode: 1
psir_joint_6_position_controller:
  type: position_controllers/JointPositionController
  joint: psir_joint_6
  required_drive_mode: 1

## velocity controller
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
     - psir_joint_1
     - psir_joint_2
     - psir_joint_3
     - psir_joint_4
     - psir_joint_5
     - psir_joint_6
  required_drive_mode: 2

psir_joint_1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: psir_joint_1
  required_drive_mode: 2
psir_joint_2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: psir_joint_2
  required_drive_mode: 2
psir_joint_3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: psir_joint_3
  required_drive_mode: 2
psir_joint_4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: psir_joint_4
  required_drive_mode: 2
psir_joint_5_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: psir_joint_5
  required_drive_mode: 2
psir_joint_6_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: psir_joint_6
  required_drive_mode: 2
