controller_list:
  - name: fake_manipulator_controller
    joints:
      - psir_joint_1
      - psir_joint_2
      - psir_joint_3
      - psir_joint_4
      - psir_joint_5
      - psir_joint_6
  - name: fake_manipulator_ensenso_controller
    joints:
      - psir_joint_1
      - psir_joint_2
      - psir_joint_3
      - psir_joint_4
      - psir_joint_5
      - psir_joint_6
  - name: fake_manipulator_asus_controller
    joints:
      - psir_joint_1
      - psir_joint_2
      - psir_joint_3
      - psir_joint_4
      - psir_joint_5
      - psir_joint_6
  - name: fake_manipulator_tcp_controller
    joints:
      - psir_joint_1
      - psir_joint_2
      - psir_joint_3
      - psir_joint_4
      - psir_joint_5
      - psir_joint_6